language: python
python:
  - "3.12"
install:
  - pip install sphinx
  - pip install black codecov coverage
script:
  - black --check entrypoint.py sphinx_action tests
  - coverage run --omit="*/tests*" -m unittest
after_success:
  - codecov
